# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PinState.xdc

# Block Designs: bd/Measure/Measure.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Measure || ORIG_REF_NAME==Measure} -quiet] -quiet

# IP: bd/Measure/ip/Measure_processing_system7_0_0/Measure_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Measure_processing_system7_0_0 || ORIG_REF_NAME==Measure_processing_system7_0_0} -quiet] -quiet

# IP: bd/Measure/ip/Measure_Top_Module_0_0/Measure_Top_Module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Measure_Top_Module_0_0 || ORIG_REF_NAME==Measure_Top_Module_0_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: bd/Measure/ip/Measure_axi_gpio_0_0/Measure_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Measure_axi_gpio_0_0 || ORIG_REF_NAME==Measure_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Measure/ip/Measure_axi_smc_0/Measure_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Measure_axi_smc_0 || ORIG_REF_NAME==Measure_axi_smc_0} -quiet] -quiet

# IP: bd/Measure/ip/Measure_rst_ps7_0_50M_0/Measure_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Measure_rst_ps7_0_50M_0 || ORIG_REF_NAME==Measure_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Measure/ip/Measure_axi_gpio_1_1/Measure_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Measure_axi_gpio_1_1 || ORIG_REF_NAME==Measure_axi_gpio_1_1} -quiet] -quiet

# XDC: g:/15F/project_backup2/project_backup2.gen/sources_1/bd/Measure/Measure_ooc.xdc
