# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/15F/project_backup2/project_backup2.srcs/sources_1/bd/Measure/ip/Measure_processing_system7_0_0/Measure_processing_system7_0_0.xci
# IP: The module: 'Measure_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/15F/project_backup2/project_backup2.gen/sources_1/bd/Measure/ip/Measure_processing_system7_0_0/Measure_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Measure_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: G:/15F/project_backup2/project_backup2.srcs/sources_1/bd/Measure/ip/Measure_processing_system7_0_0/Measure_processing_system7_0_0.xci
# IP: The module: 'Measure_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/15F/project_backup2/project_backup2.gen/sources_1/bd/Measure/ip/Measure_processing_system7_0_0/Measure_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Measure_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
