# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/15F/project_backup2/project_backup2.srcs/sources_1/bd/Measure/ip/Measure_Top_Module_0_0/Measure_Top_Module_0_0.xci
# IP: The module: 'Measure_Top_Module_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: G:/15F/project_backup2/project_backup2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: G:/15F/project_backup2/project_backup2.srcs/sources_1/bd/Measure/ip/Measure_Top_Module_0_0/Measure_Top_Module_0_0.xci
# IP: The module: 'Measure_Top_Module_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: G:/15F/project_backup2/project_backup2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
